- name: Prepare pastel instance
  hosts: root
  tasks:
    - name: Add user 'animecoinuser'
      shell: adduser --disabled-password --gecos "" animecoinuser

    - name: Set its password
      shell: echo animecoinuser:taksa123 | chpasswd

    - name: Install libgomp1
      shell: apt update && apt install -y libgomp1 

    - name: Install git-lfs
      shell: apt install -y git-lfs

    - name: Install PIP3
      shell: apt install -y python3-pip
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install software-properties-common
      shell: apt install -y software-properties-common

    - name: Install python3-distutils
      shell: apt install -y python3-distutils

    - name: Install virtualenv
      shell: pip3 install virtualenv

    - name: Update sqlite version
      shell: wget https://dobrushskiy.name/static/libsqlite3.so.0 && mv libsqlite3.so.0 /usr/lib/x86_64-linux-gnu/libsqlite3.so.3.31 && ln -sf /usr/lib/x86_64-linux-gnu/libsqlite3.so.3.31 /usr/lib/x86_64-linux-gnu/libsqlite3.so.0

    - name: Add ssh key for animecoinuser
      become: yes
      become_user: animecoinuser
      become_method: su
      shell: mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDk38NuRUpLO5V0U7wi/R0DL1+Bkf03bSRTx44mZ6MyyGaXIGlgUwh8qpnYPCg1r9vk4Vs47UteRbaouyKuafyiFoQuBpghqmxMuPrRVz/WumD/5rBcV3CRCt7ussXZ7Xamuw/anlzaxhFue9LpJYC1q6Gkb1fpZVI3R80iyQGU5WBLi7ATMsYce4MhPtUpx+rVCneDdyzuexTjfD2U+dSKBPZVZSu2GmjbUgjqbKMbzM1+54WSIFrEBFI6MLSOxosWt9ih2qK9qJU82SjBAF13N8Iv4hETBTnOQfnbTqFAWh79tjRp+OE8As6Vo1jlY5e2VXZ2K+RzREf7W54A9XR9 alex@MacBook-Pro-2.local' >> ~/.ssh/authorized_keys

    - name: Get Pastel binaries
      become: yes
      become_user: animecoinuser
      become_method: su
      shell: cd /home/animecoinuser/ && wget https://dobrushskiy.name/static/pastel.tar.gz && tar -xf pastel.tar.gz && cd pastel && ./fetch-params.sh

    - name: Create pastel.conf
      become: yes
      become_user: animecoinuser
      become_method: su
      shell: mkdir ~/.pastel/ && wget https://dobrushskiy.name/static/pastel.conf && chmod +r pastel.conf && mv pastel.conf ~/.pastel/pastel.conf
